#! /bin/bash

DOXYFILE=$1
FEEDNAME=$2
BUNDLE_ID=$3

cat >> ${DOXYFILE} <<EOL
GENERATE_DOCSET = YES
DOCSET_FEEDNAME = ${FEEDNAME}
DOCSET_BUNDLE_ID = ${BUNDLE_ID}
DISABLE_INDEX = YES
GENERATE_TREEVIEW = NO
SEARCHENGINE = NO
GENERATE_TAGFILE = ${BUNDLE_ID}.tag
EOL